name: flaarum # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '1.9.3' # just for humans, typically '1.2+git' or '1.3.2'
summary: A database that enforces structures # 79 char long summary
description: |
  Flaarum brings in autoindexing, table expansion
  ( a more comfortable form of joins), and supports any change
  to its table structure.

  It also supports a query language though not SQL.

  Tutorials can be found at https://sae.ng/flaarumtuts/intro

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

architectures:
  - build-on: amd64


parts:
  all-needed-files:
    # See 'snapcraft plugins'
    plugin: go
    source: .
    override-build: |
      set -xe
      go mod download
      go build -o $SNAPCRAFT_PART_INSTALL/bin/cli ./cli
      go build -o $SNAPCRAFT_PART_INSTALL/bin/prod ./prod
      go build -o $SNAPCRAFT_PART_INSTALL/bin/store ./store

      cp $SNAPCRAFT_PART_SRC/store/https-server.crt $SNAPCRAFT_PART_INSTALL/https-server.crt
      cp $SNAPCRAFT_PART_SRC/store/https-server.key $SNAPCRAFT_PART_INSTALL/https-server.key


apps:
  cli:
    command: bin/cli
    plugs:
      - network

  prod:
    command: bin/prod

  store:
    command: bin/store
    daemon: simple
    restart-condition: on-abnormal
    plugs:
      - network
      - network-bind

