name: flaarum # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.9.11' # just for humans, typically '1.2+git' or '1.3.2'
summary: A database that enforces structures # 79 char long summary
description: |
  Flaarum is a database that enforces structures. It is a strict database.

  Its distinct features include table expansion (a more comfortable form of joins),
  supports any change to its table structure and autoindexing.

  It also supports a query language though not SQL.

  Tutorials can be found at https://sae.ng/flaarumtuts/intro

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf


parts:
  all-needed-files:
    # See 'snapcraft plugins'
    plugin: go
    source: .
    stage-packages:
    - openssl
    build-snaps:
    - go


apps:
  cli:
    command: bin/cli
    plugs:
      - network

  genssl:
    command: bin/genssl
  
  prod:
    command: bin/prod

  store:
    command: bin/store
    daemon: simple
    restart-condition: on-abnormal
    plugs:
      - network
      - network-bind

