name: flaarum # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.5.10' # just for humans, typically '1.2+git' or '1.3.2'
summary: A database that enforces structures # 79 char long summary
description: |
  Flaarum brings in autoindexing, table expansion ( a more comfortable form of 
  joins), and supports any change to its table structure.

  It also supports a query language though not SQL.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  all-needed-files:
    # See 'snapcraft plugins'
    plugin: dump
    source: ./artifacts/flaarum.tar.xz
    source-type: tar

apps:

  cli:
    command: cli
    plugs:
      - network

  gcpasr:
    command: gcpasr
    daemon: simple
    restart-condition: on-abnormal
    plugs:
      - network

  gcprb:
    command: gcprb
    daemon: simple
    restart-condition: on-abnormal
    plugs:
      - network


  inout:
    command: inout


  lgcp:
    command: lgcp
    plugs:
      - network


  prod:
    command: prod


  store:
    command: store
    daemon: simple
    restart-condition: on-abnormal
    plugs:
      - network
      - network-bind

  statsr:
    command: statsr
    daemon: simple
    restart-condition: on-abnormal
    plugs:
      - network

  tindexer:
    command: tindexer
    daemon: simple
    restart-condition: on-abnormal